import * as fs from 'node:fs';
import * as path from 'node:path';
import * as puppeteer from 'puppeteer';
import { iconSvg } from './icon';
import { projectRoot } from './utils';

interface BaseImage {
  svg: (baseX: number, baseY: number, newWidth: number, newHeight: number) => string;
  width: number;
  height: number;
}

interface BannerImage {
  svgPath: `${string}.svg`;
  pngPath: `${string}.png`;
}

// JetBrains Mono, like the website; its glyphs are all 0.6em wide, so "C++ Here" is 4.8em.
// Ligatures are off so "++" isn't drawn as a single glyph, matching the website's logo.
const textAttributes = `fill="var(--text-color)" font-family="'JetBrains Mono', monospace" font-weight="700" style="font-variant-ligatures: none; font-feature-settings: 'calt' 0, 'liga' 0"`;

const horizontalBaseImage: BaseImage = {
  svg: (baseX, baseY, newWidth, newHeight) => `
<svg viewBox="0 0 780 200" x="${baseX}" y="${baseY}" width="${newWidth}" height="${newHeight}">
  ${iconSvg(0, 0, 200, true)}
  <text x="250" y="50%" dominant-baseline="central" ${textAttributes} font-size="110px">C++ Here</text>
</svg>
  `,
  width: 780,
  height: 200,
};

const verticalBaseImage: BaseImage = {
  svg: (baseX, baseY, newWidth, newHeight) => `
<svg viewBox="0 0 500 340" x="${baseX}" y="${baseY}" width="${newWidth}" height="${newHeight}">
  ${iconSvg(150, 0, 200, true)}
  <text x="50%" y="290" dominant-baseline="central" text-anchor="middle" ${textAttributes} font-size="90px">C++ Here</text>
</svg>
  `,
  width: 500,
  height: 340,
};

async function generateBanner(name: string, width: number, height: number): Promise<BannerImage> {
  const minMargin = Math.min(width, height) / 8;
  const availableWidth = width - minMargin * 2;
  const availableHeight = height - minMargin * 2;

  let bestImage: string = null;
  let bestTotalMargin: number = null;

  for (const baseImage of [horizontalBaseImage, verticalBaseImage]) {
    const baseRatio = Math.min(availableWidth / baseImage.width, availableHeight / baseImage.height);
    const newBaseWidth = baseImage.width * baseRatio;
    const newBaseHeight = baseImage.height * baseRatio;

    const baseX = (width - newBaseWidth) / 2;
    const baseY = (height - newBaseHeight) / 2;

    const totalMargin = baseX * 2 + baseY * 2;
    if (bestTotalMargin === null || totalMargin < bestTotalMargin) {
      bestImage = `
<!-- Generated by 'npm run generate-banners', do not edit manually -->
<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}">
  <style>
    @import url('https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@700&amp;display=block');

    :root {
      --background-color: #18181b;
      --text-color: #ffffff;
    }
  </style>
  <rect width="100%" height="100%" fill="var(--background-color)" />
  ${baseImage.svg(baseX, baseY, newBaseWidth, newBaseHeight)}
</svg>
      `.trim();

      bestTotalMargin = totalMargin;
    }
  }

  const svgPath = path.resolve(projectRoot, `media/banners/${name}.svg`) as BannerImage['svgPath'];
  const pngPath = path.resolve(projectRoot, `media/banners/${name}.png`) as BannerImage['pngPath'];

  fs.writeFileSync(svgPath, bestImage.trim() + '\n');

  return { svgPath, pngPath };
}

const requiredBanners: [string, number, number][] = [
  ['github-social-preview', 1280, 640],
  ['chrome-small-promo', 440, 280],
  ['chrome-large-promo', 920, 680],
  ['chrome-marquee-promo', 1400, 560],
];

const browser = await puppeteer.launch({
  headless: true,
});

const page = await browser.newPage();

for (const [name, width, height] of requiredBanners) {
  console.log(`Generating banner ${name} of size ${width}x${height}`);

  const banner = await generateBanner(name, width, height);

  await page.goto(`file://${banner.svgPath}`, { waitUntil: 'networkidle0' });
  await page.setViewport({ width, height });

  const fontLoaded = await page.evaluate(async () => {
    await document.fonts.ready;
    return document.fonts.check("700 16px 'JetBrains Mono'");
  });
  if (!fontLoaded) {
    throw new Error('JetBrains Mono failed to load from Google Fonts');
  }

  await page.screenshot({ path: banner.pngPath });
}

await browser.close();
